# EuRoC
grid_row: 4
grid_col: 5
grid_min_feature_num: 3
grid_max_feature_num: 4
pyramid_levels: 3
patch_size: 15
fast_threshold: 10
max_iteration: 30
track_precision: 0.01
ransac_threshold: 3
stereo_threshold: 5